[package]
name = "dota2_webapi_bindings"
version = "0.6.0"
edition = "2018"
license = "MIT"

[dependencies]
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"
serde_derive = "1.0.219"
serde_with = "3.12.0"
